version: '3.8'

services:
  # MySQL Database
  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: inovacamp_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-inovacamp_secure_password_2024}
      MYSQL_DATABASE: ${DB_NAME:-inovacamp_db}
      MYSQL_USER: ${DB_USER:-inovacamp_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-inovacamp_secure_password_2024}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - inovacamp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-inovacamp_secure_password_2024}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inovacamp_backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-inovacamp_db}
      DB_USER: ${DB_USER:-inovacamp_user}
      DB_PASSWORD: ${DB_PASSWORD:-inovacamp_secure_password_2024}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inovacamp_network
    restart: unless-stopped

  # Nginx (Reverse Proxy & Load Balancer)
  nginx:
    image: nginx:alpine
    container_name: inovacamp_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    networks:
      - inovacamp_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  inovacamp_network:
    driver: bridge